[versions]
kotlin = "2.1.10"
kotest = "5.9.1"
mockito = "5.15.2"
proto = "4.29.3"
grpc = "1.70.0"
grpc-kotlin = "1.4.1"
protobuf = "0.9.4"
ktorm = "4.1.1"
mockk = "1.13.16"
postgresql = "42.7.5"
dotenv = "6.5.1"
ktor = "3.1.1"
avro = "1.12.0"
shared-kernel = "1.0.0"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotest-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-kotlin-stub", version.ref = "grpc-kotlin" }
grpc-testing = { module = "io.grpc:grpc-testing", version.ref = "grpc" }
grpc-generator-java = { module = "io.grpc:protoc-gen-grpc-java", version.ref = "grpc" }
grpc-generator-kotlin = { module = "io.grpc:protoc-gen-grpc-kotlin", version = "1.4.1:jdk8@jar" }
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "proto" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "proto" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "proto" }
javax-annotation-api = { module = "javax.annotation:javax.annotation-api", version = "1.3.2" }
ktorm-core = { module = "org.ktorm:ktorm-core", version.ref = "ktorm" }
ktorm-postgresql = { module = "org.ktorm:ktorm-support-postgresql", version.ref = "ktorm" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
dotenv = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenv" }
ktor-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
avro = { module = "org.apache.avro:avro", version.ref = "avro" }
kernel-presentation = { module = "io.github.positionpal:kernel-presentation", version.ref = "shared-kernel" }
kernel-domain = { module = "io.github.positionpal:kernel-domain", version.ref = "shared-kernel" }
slf4j = { module = "org.slf4j:slf4j-simple", version = "2.0.17" }
rabbit-amqp = { module = "com.rabbitmq:amqp-client", version = "5.25.0" }
jbcrypt = { module = "org.mindrot:jbcrypt", version = "0.4" }

[bundles]
kotlin-testing = [ "kotest-junit5-jvm", "kotest-assertions-core-jvm", "mockito-core" ]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = "org.danilopianini.gradle-kotlin-qa:0.69.0"
kotlin-dokka = { id = "org.jetbrains.dokka", version = "2.0.0" }
git-semantic-versioning = "org.danilopianini.git-sensitive-semantic-versioning:4.0.2"
protobuf = {id = "com.google.protobuf", version.ref = "protobuf"}
shadowJar = "com.github.johnrengelman.shadow:8.1.1"
gradle-docker-compose = "com.avast.gradle.docker-compose:0.17.12"

