name: Build, Test and Check

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2022]
        jvm-version: [ 11, 17, 21 ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up JDK ${{ matrix.jvm-version }}
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jvm-version }}
      - name: Assemble main and test classes
        run: ./gradlew classes testClasses

      - name: Run tests for storage submodule
        if: contains(matrix.os, 'ubuntu')
        run: ./gradlew :storage:test

      - name: Run tests for other submodules
        run: ./gradlew test -x :storage:test

      - name: Check storage submodule
        if: contains(matrix.os, 'ubuntu')
        run: ./gradlew :storage:check

      - name: Check for other submodules
        run: ./gradlew check -x :storage:check

  success:
    needs:
      - build
    if: >- # run if at least one needed job has failed or all needed jobs have not been cancelled or skipped
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || (
          !contains(join(needs.*.result, ','), 'cancelled') 
          && !contains(join(needs.*.result, ','), 'skipped')
        )
      )
    runs-on: ubuntu-24.04
    steps:
      - name: Verify no failures occurred in needed jobs
        # if there are failures, false is executed and the job fails.
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}

  deploy:
    needs:
      - success
    uses: ./.github/workflows/publish.yml
    if: github.ref_name == 'master' || github.ref_name == 'main'
    secrets: inherit

  publish-api-doc:
    needs:
      - success
    uses: ./.github/workflows/dokka-gh-pages.yml
    if: github.ref_name == 'master' || github.ref_name == 'main'
    secrets: inherit
